### ISSUE TITLE
markdown code blocks do not work

### ISSUE THREAD

**Issue by mrbinky3000** [javiercf/react-markdown-loader#15]
The following results in an error

```
\`\`\`
This is a code block
\`\`\`
```

```
ERROR in ./src/Brander/README.md
Module build failed: TypeError: Cannot read property 'rest' of undefined
    at Object._self.Prism.tokenize (/my-project/node_modules/prismjs/prism.js:265:21)
    at Object._self.Prism.highlight (/my-project/node_modules/prismjs/prism.js:256:18)
    at Function.highlight (/my-project/node_modules/react-markdown-loader/src/parser.js:86:22)
    at Object.rules.fence (/my-project/node_modules/remarkable/lib/rules.js:73:37)
    at Renderer.render (/my-project/node_modules/remarkable/lib/renderer.js:71:39)
    at Remarkable.render (/my-project/node_modules/remarkable/lib/index.js:152:24)

    at err (/my-project/node_modules/react-markdown-loader/src/parser.js:105:17)
    at parseMarkdown (/my-project/node_modules/react-markdown-loader/src/parser.js:81:10)
    at Object.parse (/my-project/node_modules/react-markdown-loader/src/parser.js:132:10)
    at Object.module.exports (/my-project/node_modules/react-markdown-loader/src/index.js:16:6)
```

**Comment by javiercf** [comment]
can you comment what version of node and webpack you are using?

**Comment by therise3107** [comment]
I am also facing the same issue is there any way around?
